name: Generate Next.js Routes JSON

on:
  push:
    branches:
      - main

# Grant write permissions to commit the file back to the repo
permissions:
  contents: write

jobs:
  build-routes-json:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your Next.js project code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Use Gemini CLI to find page files and generate JSON
      - name: Generate routes.json from /app directory
        uses: google-gemini/gemini-cli-action@main # <-- Corrected version tag
        with:
          # Make sure GEMINI_API_KEY is set in your repo's secrets
          api-key: ${{ secrets.GEMINI_API_KEY }}
          exec: |
            find ./app -name "page.tsx" -o -name "page.jsx" | gemini "Based on the file paths below, create a JSON object. It should have a 'routes' key with an array of URL path strings (e.g., './app/about/page.tsx' becomes '/about', './app/page.tsx' becomes '/'). Output only the clean, raw JSON, with no markdown formatting." > public/data/routes.json

      # 3. Verify the file was created
      - name: Verify file content
        run: |
          echo "Verifying routes.json..."
          mkdir -p public/data
          cat public/data/routes.json

      # 4. Commit and push the generated file
      - name: Commit and push the generated file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(routes): Auto-update routes JSON file"
          file_pattern: "public/data/routes.json"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions-bot@users.noreply.github.com"