name: Generate English Essay Examples

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      topic:
        description: '请输入英语作文的主题（选填）'
        required: false
        default: 'PET (B1 Preliminary) 考试的写作要求'

permissions:
  contents: write

jobs:
  generate-essay-json:
    runs-on: ubuntu-latest
    steps:
      # 1-4 步保持不变
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Gemini CLI
        run: npm install -g @google/gemini-cli
      - name: Create output directory
        run: mkdir -p public/data

      # 5. 核心步骤：构建指令，并将其作为输入传递
      - name: Generate and save essay examples
        run: |
          # 根据触发方式构建不同的指令内容
          if [[ "${{ github.event.inputs.topic }}" != "" && "${{ github.event.inputs.topic }}" != "PET (B1 Preliminary) 考试的写作要求" ]]; then
            echo "使用手动输入的主题生成作文: ${{ github.event.inputs.topic }}"
            PROMPT="请为我生成一个JSON文件内容，其中包含两篇关于主题“${{ github.event.inputs.topic }}”的英语作文案例。每篇作文大约100个单词，并提供中文翻译。JSON的结构应该如下：根对象是一个包含'essays'键的数组，每个对象都应包含 'title', 'english_text', 和 'chinese_translation' 这三个键。请确保只输出纯净、格式正确的JSON。"
          else
            echo "使用默认的 PET 主题生成作文"
            PROMPT="请为我生成一个JSON文件内容，其中包含两个英语作文案例。这两个案例需要符合 PET (B1 Preliminary) 考试的写作要求，每篇作文大约100个单词。JSON的结构应该如下：根对象是一个包含'essays'键的数组，每个对象都应包含 'title', 'english_text', 和 'chinese_translation' 这三个键。请确保只输出纯净、格式正确的JSON。"
          fi

          # 【重大修改】将 PROMPT 通过 echo 和管道 | 作为输入，而不是参数
          echo "$PROMPT" | gemini > public/data/pet-essays.json
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      # 6-7 步保持不变
      - name: Verify file content
        run: cat public/data/pet-essays.json
      - name: Commit and push the generated file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(content): 自动生成每日英语作文范文"
          file_pattern: "public/data/pet-essays.json"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions-bot@users.noreply.github.com"